# This is a basic workflow to help you get started with Actions

name: leapCircle-release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 读取webApp json 的信息
        uses: antifree/json-to-variables@v1.0.1
        with:
          filename: 'webApp.json'
          prefix: webApp
      - name: 打包成zip
        run: |
          zip -q -r leapCircle.zip ./
          ls
          echo "The time was ${{ env.webApp_version }}, ${{ env.webApp_name }}"
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ env.webApp_version }}
          release_name: v${{ env.webApp_version }}
          body_path: "leapCircle.zip"
          body: |
            update
          draft: false
          prerelease: false
